### PR TITLE
Add gradle + Standard project structure

### LINKED ISSUE #19: Update project layout?
Hello

I'm trying to run the code locally and the way it is now, it involves a lot of _manual_ work to make it work. 
Would you consider accepting a Pull Request where I add gradle for dependency management, and also update he folder structure a bit?

### PR DESCRIPTION
**Pull request by TheBestPessimist**
This PR adds gradle support for dependencies, and also updates the code to a structured layout.

Left to to (if desired by @Mamiglia ):
- [x] add a main package, ie. `com.mamiglia`
- [x] relocate `.build` folder (to where?)
- [x] relocate `Installer` folder (to where?)

Fixes: https://github.com/Mamiglia/Reddit-Wallpaper/issues/19

### CODE REVIEW

**Comment by TheBestPessimist** [comment]
@Mamiglia what JNA library are u using?

I tried to use `net.java.dev.jna:jna:5.8.0` from https://search.maven.org/artifact/net.java.dev.jna/jna/5.8.0/jar, however it does not contain the package `com.sun.jna.platform`, as you can see from the screenshot below.

image


Later edit:

Nvm, the answer is obvious, it's JNA Platform: https://search.maven.org/artifact/net.java.dev.jna/jna-platform/5.8.0/jar

**Comment by Mamiglia** [comment]
I saw a todo, asking for which is the current version. It is 1.2.1

For JNA: It's JNA-platform

**Comment by TheBestPessimist** [comment]
The changes should almost be finished, however i have the following error when running:
image

**Comment by Mamiglia** [comment]
It doesn't find the icon which was in "/resources/tray_icon.png". you probably moved it. Set the correct path at line 18 of Tray.java

**Comment by TheBestPessimist** [comment]
Works, it changes my wallpaper!


Another issue: when i right click tray and click `settings`, it gives another error:
image

**Comment by Mamiglia** [comment]
I can't understand the error at the moment, I will look further into this tomorrow

**Comment by TheBestPessimist** [comment]
In that case, please check the PR. Check the left TODOs in the description, and think if you desire to change those. 
I didn't check how they work, so you might need to instruct me, or test yourself.

When checking the PR, each commit can be read chronologically, so that you see what I changed and why.

If you think my PR is good enough, feel free to merge.
If you think changes are still needed, please ask for those changes.

If something doesn't make sense, please ask.

**Comment by Mamiglia** [comment]
Ok, the issue was caused by gradle not building the Intellij Swing desgner that I used to design the UI. I changed a setting in Intellij to make it work: https://stackoverflow.com/a/55725767/9419492 read the comments if your Intellij is > 2019.1

**Comment by Mamiglia** [comment]
Ok now the only thing left is the `.build` folder: where does it belong? It's a folder containing all the necessary files that I use together with Install4j, which is an external program that creates the installer

**Comment by TheBestPessimist** [comment]
I have never used Install4j, however since it's not part of the source code, nor is it a resource needed during application run, it can stay in project root folder as it is now.

**Comment by TheBestPessimist** [comment]
> gradle not building the Intellij Swing desgner

I suggest you go and 👍 this issue and the 2 related ones, so that Jetbrains sees if people are affected by it: https://youtrack.jetbrains.com/issue/IDEA-223518

It seems to be mentioned in the docs as well, the green box at the top: https://www.jetbrains.com/help/idea/gui-designer.html.

This is unfortunate (maybe?) because with gradle you could have created the jar for the project simply by running `gradlew jar`. Maybe in your case this is not a problem as you are using install4j to generate the installer.

**Comment by Mamiglia** [comment]
Ok, added the 👍 to the issue. I did find this plugin that should've handled the thing automatically https://github.com/File5/intellij-idea-guidesigner-plugin, but probably due to my inexperience I couldn't make it work

**Comment by TheBestPessimist** [comment]
You can add the plugin and push and i will check it out. That's the best way to learn how to use gradle.

**Comment by Mamiglia** [comment]
Tried to add the plugin as described by the github page, but still it doesn't work if I don't enable the right setting in the settings. I even tried some variations, but no way to make it work, it always give some error about a missing class (I think  it's a class needed for the UI builder).
If we can't find a way to make it work I'll just revert the last commit

**Comment by TheBestPessimist** [comment]
Yep, i cant figure it out either, sorry. `¯\_(ツ)_/¯`

Just revert then merge.

**Comment by Mamiglia** [comment]
Thanks for all the help!

**Pull request merged**
